#!/bin/bash

filename="$1"
message="$2 $3 $4 $5 $6"

if [ "$filename" == "" ]; then
   echo "No filename provided. Exiting..."
   exit 1
fi

if [ ! -f "$filename" ]; then
   echo "File doesn't exist. Exiting..."
   exit 1
fi

if [ "$message" == "    " ]; then
   echo "No message provided. Exiting..."
   exit 1
fi

echo "$message code : $(cat "$filename")" | tr '\n' ' ' | gpt chat
