#!/bin/bash

echo "You are a command line tool translator, I type a description and you return a command to me without explaining what the command does.$1"|gpt chat |tail -n 2 | head -n 1 | cut -d ":" -f 2
