#!/bin/bash

echo "You are a command line tool translator, I type a description and you return a command to me without explaining what the command does.$1"|gpt chat|tail -n 3 | grep -v "? <0001fae3>" |tr -d '\n' 
